### ISSUE TITLE
Installation with pip fails

### ISSUE THREAD

**Issue by jaasal** [zero-88/robotframework-excel#9]
**Describe the bug**
pip install robotframework-excel --upgrade stops with the following error:

```
C:\Projektit\vagrant>pip install robotframework-excel==1.0.0b4
Collecting robotframework-excel==1.0.0b4
  Using cached https://files.pythonhosted.org/packages/94/a5/0ad71fa8aa83b79bfa6d5c0a004e0eef496f311642023d962a4639b94927/robotframework-excel-1.0.0b4.tar.gz
    Complete output from command python setup.py egg_info:
    1.0.0b4
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jaakko\appdata\local\temp\pip-install-i2cmdl\robotframework-excel\setup.py", line 56, in <module>
        _REQUIRES, _LINKS, = __gather_dependencies('requirements.txt')
      File "c:\users\jaakko\appdata\local\temp\pip-install-i2cmdl\robotframework-excel\setup.py", line 42, in __gather_dependencies
        for item in requirements:
      File "c:\python27\lib\site-packages\pip\_internal\req\req_file.py", line 82, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "c:\python27\lib\site-packages\pip\_internal\download.py", line 440, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip._internal.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```
**Environment**
- Library Version: 1.0.0b4
- Python Version: 2.7.15
- OS: Windows 10 & Ubuntu 16.x

**To Reproduce**
1. Execute command: pip install robotframework-excel --upgrade

**Exception Log**
See description

**Expected behavior**
Installation succeeds.

**Comment by Tony36051** [comment]
It seems that @zero-88 didn't pack `requirements.txt` into `robotframework-excel-1.0.0b4.tar.gz` .Please fix it. 

By the way, please fix the version of `xlwt`!  
Becasuse xlutils==2.0.0 didn't help to fix the version of xlwt, older version of xlwt can lead writing error in get_sheet( not so accurate memory)

**Comment by zero-88** [comment]
Thank @Tony36051 @jaasal 
I will find a time in this weekend to have a look the dependencies.
For workaround, you can install lib directly via github:
`pip install https://github.com/zero-88/robotframework-excel/archive/master.zip`

**Comment by xrcm** [comment]
robotframework-excel 1.0.0 has requirement natsort==5.2.0, but you'll have natsort 6.0.0 which is incompatible.
robotframework-excel 1.0.0 has requirement openpyxl==2.5.1, but you'll have openpyxl 2.6.1 which is incompatible.

It is really necessary these 2 dependencies with these exact versions?
